apiVersion: v1
kind: Secret
metadata:
  name: zabbix-db-secret
  namespace: zabbix
type: Opaque
data:
  db_host: MTkyLjE2OC4xODguMTY4
  db_name: emFiYml4
  db_user: emFiYml4Mg==
  db_password: emFiYml4QDEyMzQ1Ng==

