apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-server
  namespace: zabbix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-server
  template:
    metadata:
      labels:
        app: zabbix-server
    spec:
      containers:
      - name: zabbix-server
        image: zabbix/zabbix-server-mysql:latest
        ports:
        - containerPort: 10051
        env:
        - name: DB_SERVER_HOST
          valueFrom:
            secretKeyRef:
              name: zabbix-db-secret
              key: db_host
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: zabbix-db-secret
              key: db_name
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: zabbix-db-secret
              key: db_user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: zabbix-db-secret
              key: db_password
        - name: ZBX_STARTUP_DB
          value: "1"

