apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-frontend
  namespace: zabbix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-frontend
  template:
    metadata:
      labels:
        app: zabbix-frontend
    spec:
      containers:
      - name: zabbix-frontend
        image: zabbix/zabbix-web-nginx-mysql:latest
        ports:
        - containerPort: 8080
        env:
        - name: DB_SERVER_HOST
          valueFrom:
            secretKeyRef:
              name: zabbix-db-secret
              key: db_host
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: zabbix-db-secret
              key: db_name
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: zabbix-db-secret
              key: db_user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: zabbix-db-secret
              key: db_password
        - name: ZBX_SERVER_HOST
          value: "zabbix-server-service"
        - name: ZBX_SERVER_PORT
          value: "10051"
        - name: ZBX_SERVER_NAME
          value: "Zabbix Server"
